version: "3.8"

services:
  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - ./fe:/app/fe
      - /app/fe/node_modules
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app/api
